### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by firasdib**

### CODE REVIEW

**Comment by dy** [comment]
@chrisbateman any reaction?

**Comment by dy** [comment]
@chrisbateman ping

**Comment by firasdib** [comment]
@dy I have sent the author an email last week, but have not received a response yet.

**Comment by dy** [comment]
@firasdib ping

**Comment by firasdib** [comment]
@dy no response from the author though?

**Comment by chrisbateman** [comment]
Sorry for the delay

**Pull request merged**
